openapi: 3.0.3
info:
  title: AILab API
  description: API for AILab application that integrates with LangChain4j
  version: 1.0.0
  contact:
    name: Jose Manzano
    email: jmanzanog@icloud.com
    url: https://github.com/jmanzanog
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: http://localhost:8080
    description: Local development server
tags:
  - name: LangChain Version
    description: API to retrieve LangChain4j version information
paths:
  /api/langchain/versions:
    get:
      tags:
        - LangChain Version
      summary: Get LangChain4j versions
      description: Returns information about the supported LangChain4j versions
      operationId: getLangChainVersions
      responses:
        '200':
          description: Successfully retrieved version information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'
        '500':
          description: Internal server error

  /api/embedding/execute:
    post:
      tags:
        - embedding
      summary: Execute Creation embedding process
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                param1:
                  type: string
              required:
                - param1
      responses:
        '200':
          description: Successfully asynchronous execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionOutput'


components:
  schemas:
    VersionInfo:
      type: object
      description: Version information for LangChain4j components
      properties:
        langchain4jVersion:
          type: string
          description: The version of the LangChain4j library
          example: 0.25.0
        langchain4jSpringBootStarter:
          type: string
          description: The version of the LangChain4j Spring Boot starter
          example: 0.25.0
    ExecutionOutput:
      type: object
      properties:
        execution:
          type: boolean

    EmbeddingRequest:
      type: object
      properties:
        model:
          type: string
        prompt:
          type: string
    EmbeddingResponse:
      type: object
      properties:
        embedding:
          type: array
          items:
            type: number
            format: double
        model:
          type: string
        prompt:
          type: string



